//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddressBook.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string Contact_Adding_Email_Required_Text {
            get {
                return ResourceManager.GetString("Contact_Adding_Email_Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new contact failed.
        /// </summary>
        internal static string Contact_Adding_Error_Message {
            get {
                return ResourceManager.GetString("Contact_Adding_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Adding error.
        /// </summary>
        internal static string Contact_Adding_Error_Message_Title {
            get {
                return ResourceManager.GetString("Contact_Adding_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname is required..
        /// </summary>
        internal static string Contact_Adding_Fullname_Required_Text {
            get {
                return ResourceManager.GetString("Contact_Adding_Fullname_Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required..
        /// </summary>
        internal static string Contact_Adding_Phone_Required_Text {
            get {
                return ResourceManager.GetString("Contact_Adding_Phone_Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New contact added successfully!.
        /// </summary>
        internal static string Contact_Adding_Successful_Message {
            get {
                return ResourceManager.GetString("Contact_Adding_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add successfull.
        /// </summary>
        internal static string Contact_Adding_Successful_Message_Title {
            get {
                return ResourceManager.GetString("Contact_Adding_Successful_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Updating error.
        /// </summary>
        internal static string Contact_Updating_Error_Message_Title {
            get {
                return ResourceManager.GetString("Contact_Updating_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Regard?.
        /// </summary>
        internal static string Delete_Check_Message {
            get {
                return ResourceManager.GetString("Delete_Check_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Delete_Check_Message_Title {
            get {
                return ResourceManager.GetString("Delete_Check_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact details deleted successfully.
        /// </summary>
        internal static string Delete_Successful_Message {
            get {
                return ResourceManager.GetString("Delete_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successfull.
        /// </summary>
        internal static string Delete_Successful_Message_Title {
            get {
                return ResourceManager.GetString("Delete_Successful_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the email.
        /// </summary>
        internal static string Email_Error_Message {
            get {
                return ResourceManager.GetString("Email_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email error.
        /// </summary>
        internal static string Email_Error_Message_Title {
            get {
                return ResourceManager.GetString("Email_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the following..
        /// </summary>
        internal static string Error_Message_Header {
            get {
                return ResourceManager.GetString("Error_Message_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! System error. Please contact administrator..
        /// </summary>
        internal static string System_Error_Message {
            get {
                return ResourceManager.GetString("System_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Message.
        /// </summary>
        internal static string System_Error_Message_Title {
            get {
                return ResourceManager.GetString("System_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update error.
        /// </summary>
        internal static string Update_Error_Message_Title {
            get {
                return ResourceManager.GetString("Update_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact details updated successfully.
        /// </summary>
        internal static string Update_Successful_Message {
            get {
                return ResourceManager.GetString("Update_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successfull.
        /// </summary>
        internal static string Update_Successful_Message_Title {
            get {
                return ResourceManager.GetString("Update_Successful_Message_Title", resourceCulture);
            }
        }
    }
}
